title: <p align="center"> Michael Torres </p>

logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  <a href="pdf/Michael_Torres_Resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/michael-torres-46149b238/">LinkedIn</a> |
  <a href="https://github.com/Michael96Torres">GitHub</a>
  </p>
  
  <p align="justify">
  I am currently exploring new career opportunities where I can apply my diverse educational background.
  
  I hold degrees in Computer Science and Accounting, with double minors in Mathematics and Biology. 
  My studies at the University of Nevada, Las Vegas and Western Governors University have equipped me with a strong analytical foundation and a multidisciplinary perspective.
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID

