title: <p align="center"> Michael Torres </p>

logo: "/images/picture.png?raw=true"

description:
  <p align="justify">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/michael-torres-46149b238/">LinkedIn</a> |
  <a href="https://github.com/Michael96Torres">GitHub</a>
  </p>
  
  <p align="center">
  Recently graduated with a degree in Computer Science and double minors in Mathematics and Biology 
  from the Univerity of Nevada, Las Vegas.
  <br><br>
  I plan on pursing an online MS degree in Analytics at the Georgia Institute of Technology.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
