title: <p align="center"> Michael Torres </p>

logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  <a href="pdf/Michael_Torres_Resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/michael-torres-46149b238/">LinkedIn</a> |
  <a href="https://github.com/Michael96Torres">GitHub</a>
  </p>
  
  <p align="justify">
  Currently hold degrees in Computer Science and double minors in Mathematics and Biology 
  from the University of Nevada, Las Vegas as well as an Accounting degree from Western Governors 
  University.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID

